apiVersion: v1
kind: ConfigMap
metadata:
  name: task-manager-config
  namespace: task-manager
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  ASPNETCORE_URLS: "http://+:80"
  POSTGRES_DB: "TaskManagerDB"
  POSTGRES_USER: "postgres"
  RABBITMQ_DEFAULT_USER: "admin"
  RABBITMQ_DEFAULT_PASS: "admin123"
  API_KEY: "abc-123"
  MAX_ITEMS_PER_PAGE: "10"
