apiVersion: v1
kind: Secret
metadata:
  name: task-manager-secrets
  namespace: task-manager
type: Opaque
data:
  # postgres_password123 encoded in base64
  postgres-password: cG9zdGdyZXNfcGFzc3dvcmQxMjM=
  # admin123 encoded in base64
  rabbitmq-password: YWRtaW4xMjM=
