apiVersion: v1
kind: Service
metadata:
  name: task-manager-api
  namespace: task-manager
  labels:
    app: task-manager-api
spec:
  selector:
    app: task-manager-api
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  type: ClusterIP
