apiVersion: v1
kind: ConfigMap
metadata:
  name: "#{APP_NAME}#"
  namespace: "#{APP_NAME}#"
data:
  ASPNETCORE_ENVIRONMENT: "#{ASPNETCORE_ENVIRONMENT}#"
  CONNECTION_STRING: "#{CONNECTION_STRING}#"
  RABBITMQ_HOSTNAME: "#{RABBITMQ_HOSTNAME}#"
  RABBITMQ_PORT: "#{RABBITMQ_PORT}#"
  RABBITMQ_USERNAME: "#{RABBITMQ_USERNAME}#"
  RABBITMQ_PASSWORD: "#{RABBITMQ_PASSWORD}#"