apiVersion: apps/v1
kind: Deployment
metadata:
  name: "#{APP_NAME}#"
  namespace: "#{APP_NAME}#"
  labels:
    app: "#{APP_NAME}#"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "#{APP_NAME}#"
  template:
    metadata:
      labels:
        app: "#{APP_NAME}#"
    spec:
      containers:
        - name: "#{APP_NAME}#"
          image: "#{ECR_REPOSITORY_URL}#/#{APP_NAME}#:#{TAG}#"
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: "#{APP_NAME}#"
          resources:
            requests: 
              memory: "128Mi"
              cpu: "250m" 
            limits:
              memory: "256Mi"
              cpu: "500m" 
