apiVersion: v1
kind: Namespace
metadata:
  name: q10-task-manager
  labels:
    name: q10-task-manager
    app: task-manager
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: q10-config
  namespace: q10-task-manager
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  CONNECTION_STRING: "Host=10.110.96.145;Port=15433;Database=TaskManagerDB;User Id=postgres;Password=postgres_password123"
  RABBITMQ_HOSTNAME: "10.104.182.199"
  RABBITMQ_PORT: "5672"
  RABBITMQ_USERNAME: "admin"
  RABBITMQ_PASSWORD: "admin123"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: q10-deployment
  namespace: q10-task-manager
  labels:
    app: q10
spec:
  replicas: 1
  selector:
    matchLabels:
      app: q10
  template:
    metadata:
      labels:
        app: q10
    spec:
      containers:
        - name: q10
          image: andreslon/q10-api:1.0.0
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: q10-config
          resources:
            requests: 
              memory: "128Mi"
              cpu: "250m" 
            limits:
              memory: "256Mi"
              cpu: "500m" 
---
apiVersion: v1
kind: Service
metadata:
  name: q10-service
  namespace: q10-task-manager
spec:
  selector:
    app: q10
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 80
      
