apiVersion: v1
kind: Service
metadata:
  name: "#{APP_NAME}#"
  namespace: "#{APP_NAME}#"
spec:
  selector:
    app: "#{APP_NAME}#"
  type: LoadBalancer    
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      
