name: CI/CD API
on:
  push:
    branches: ["dev","main"]
    paths:
      - 'api/**'
      - 'kubernetes/**'
      - 'api.Dockerfile'
      - '.github/workflows/ci-cd-api.yml'
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason for the deployment'
        required: true
        default: 'Manual deployment'

env:
  Environment: ${{ github.ref_name }}
  TAG: ${{ github.sha }}
  SLN_PATH: 'api/Q10.TaskManager.Api.sln'
  API_IMAGE_NAME: 'q10-api'
  ECR_REPOSITORY_URL: '394901908314.dkr.ecr.us-east-1.amazonaws.com'

jobs:
  CI-Native:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Restore .Net packages
        run: dotnet restore ${{ env.SLN_PATH }}
      - name: Build the project
        run: dotnet build ${{ env.SLN_PATH }} -c Release
      - name: Test the project
        run: dotnet test ${{ env.SLN_PATH }}

  CI-Docker:
    runs-on: ubuntu-latest
    needs: CI-Native
    steps:
      - name: Checkout code
        uses: actions/checkout@v2    
      - name:
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Build the Docker image
        run: docker build -t ${{ env.ECR_REPOSITORY_URL }}/${{ env.API_IMAGE_NAME }}:${{ env.TAG }} -f "api.Dockerfile" "." 
        
      - name: Push the Docker image
        run: docker push ${{ env.ECR_REPOSITORY_URL }}/${{ env.API_IMAGE_NAME }}:${{ env.TAG }}

  # CD-Docker:
  #   runs-on: ubuntu-latest
          